#!/bin/bash

set -x

AVR_GDB='/Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/bin/avr-gdb'

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# cgdb -d"$AVR_GDB" -- -x"$DIR/.gdbinit" $@
cp "$DIR/.gdbinit" ./
cgdb -d"$AVR_GDB" $@
